name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate config.js with API key
        run: |
          echo "window.myAppConfig = { apiKey: '${{ secrets.API_KEY }}' };" > config.js

      - name: Build site (optional)
        run: |
          echo "Building your static files..."

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./